# MIT licensed
name: openMINDS_documentation_build_pipeline

on:
  workflow_dispatch:
  push:
      branches:
        - pipeline
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        path: pipeline
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Checkout documentation branch
      uses: actions/checkout@v3
      with:
        path: upload
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run build
      run: |
        cd pipeline
        ls -alh
        pip install -r requirements.txt
        python build.py

